#!/bin/sh

echo Component: $VCI_COMPONENT_NAME
echo Model:     $VCI_MODEL_NAME
echo Message:   $EPHEMERA_MESSAGE
echo '{"error-type":"application","error-severity":"error","error-tag":"operation-failed","error-message":"foo bar"}' 1>&2
exit 1
